### PR TITLE
Moved TestFixture back into the Test directory

### PR DESCRIPTION
**Pull request by TheyCallMeHacked**

### CODE REVIEW

**Review by lumeto-de-diamanto — CHANGES_REQUESTED** [review]
We should get rid of one of the TestFixture files instead. Code duplication is unbecoming.

**Comment by TheyCallMeHacked** [comment]
> We should get rid of one of the TestFixture files instead. Code duplication is unbecoming.

What do you mean ? There is no code duplication. This is litterally replacing the old `Tests/TestFixture` with the new `TestFixture`. It just doesn't make sense to have it stay in the root directory. It also doesn't make sense to keep the old quasi-empty one...

**Comment by TheyCallMeHacked** [comment]
Oopsies... mea culpa, I actually forgot to add the removal of the old file to the MR...

**Review by lumeto-de-diamanto — APPROVED** [review]
👍

**Pull request merged**
